package com.bike.rent.kelly.utils

import com.bike.rent.kelly.R

object BikeArray {
    var bikeimages = mutableListOf(
        R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30, R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30, R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30, R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30,R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30,R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30,R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30,R.drawable.bicycle_0, R.drawable.bicycle_1, R.drawable.bicycle_2, R.drawable.bicycle_3,
        R.drawable.bicycle_4, R.drawable.bicycle_5, R.drawable.bicycle_6, R.drawable.bicycle_7, R.drawable.bicycle_8,
        R.drawable.bicycle_9, R.drawable.bicycle_10, R.drawable.bicycle_11, R.drawable.bicycle_12, R.drawable.bicycle_13,
        R.drawable.bicycle_14, R.drawable.bicycle_15, R.drawable.bicycle_16, R.drawable.bicycle_17, R.drawable.bicycle_18,
        R.drawable.bicycle_19, R.drawable.bicycle_20, R.drawable.bicycle_21, R.drawable.bicycle_22, R.drawable.bicycle_23,
        R.drawable.bicycle_24, R.drawable.bicycle_25, R.drawable.bicycle_26, R.drawable.bicycle_27, R.drawable.bicycle_28,
        R.drawable.bicycle_29, R.drawable.bicycle_30)
}